import React,{useEffect,useRef,useState} from 'react';
import TokenLogo from './TokenLogo';
import {fetchFarmPortfolio,reviewFarmClaim,executeFarmClaim,reviewAllFarmClaims,executeAllFarmClaims,reviewFarmUnstake,executeFarmUnstake} from '../services/alcorMainnet';
import './AlcorFarms.css';
import {totalFarmRewards,farmReward} from '../services/farmRewards';
import {tokenMetadata} from '../services/tokenMetadata';
export default function AlcorFarms({actor,onLogin,refresh,onClaimed}) {
 const [state,setState]=useState({loading:true,rows:[]});const [retry,setRetry]=useState(0);
 const [hideEnded,setHideEnded]=useState(()=>{try{return localStorage.getItem('cleanupcentr.farms.hideEnded')==='true';}catch{return false;}});
 useEffect(()=>{try{localStorage.setItem('cleanupcentr.farms.hideEnded',String(hideEnded));}catch{/* Optional preference. */}},[hideEnded]);
 const [review,setReview]=useState(null);const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');const [tx,setTx]=useState('');const [now,setNow]=useState(Date.now());const dialog=useRef();
 useEffect(()=>{let live=true;setState(previous=>({...previous,loading:!!actor,error:null}));if(actor)fetchFarmPortfolio(actor).then(data=>{if(live)setState(data);}).catch(e=>{if(live)setState(previous=>({...previous,loading:false,error:e.message}));});return()=>{live=false;};},[actor,refresh,retry]);
 useEffect(()=>{if(review)dialog.current.showModal();},[review]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!actor||busy||review)return;const timer=setInterval(()=>setRetry(v=>v+1),60000);return()=>clearInterval(timer);},[actor,busy,review]);
 const stale=!!state.updatedAt&&now-state.updatedAt>120000;
 const rows=state.rows.map(row=>{if(!row.incentive||!row.stake)return row;try{return {...row,...farmReward(row.incentive,row.stake,Math.floor(Math.min(now,(state.updatedAt||now)+120000)/1000))};}catch{return row;}});
 const visibleRows=hideEnded?rows.filter(row=>!row.ended):rows;
 async function prepare(row,unstake=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{setReview(unstake ? await reviewFarmUnstake(actor,row) : row ? await reviewFarmClaim(actor,row) : await reviewAllFarmClaims(actor,rows.filter(row=>!/^0+$/.test(row.raw))));setNow(Date.now());}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 async function confirm(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const result=await (review.unstake ? executeFarmUnstake(review,actor) : review.claims ? executeAllFarmClaims(review,actor) : executeFarmClaim(review,actor));setTx(result?.transactionId||result?.transaction_id||result?.processed?.id||'submitted');if(review.unstake)setState(previous=>({...previous,rows:previous.rows.filter(row=>row.posId!==review.posId||row.incentiveId!==review.incentiveId)}));setReview(null);setRetry(v=>v+1);onClaimed?.();}catch(e){setError(e.message);setReview(null);}finally{lock.current=false;setBusy(false);}}
 return <section className="exchange-card alcor-farms"><div className="exchange-card-heading"><div><div className="exchange-eyebrow">YOUR ALCOR FARMS</div><h2>Farm rewards</h2></div><a href="https://wax.alcor.exchange/farm" target="_blank" rel="noreferrer">Explore Alcor farms</a></div>
 <p className="exchange-muted">Claim rewards from your staked liquidity positions. Claims keep your positions staked; liquidity fees are collected separately.</p>
 {!actor?<button onClick={onLogin}>Connect wallet</button>:<>
 <div className="farms-toolbar"><strong>{state.loading?'Loading farms...':`${state.rows.length} staked rewards`}</strong><div className="exchange-review-actions"><button aria-pressed={hideEnded} onClick={()=>setHideEnded(value=>!value)}>{hideEnded?`Show ended farms (${rows.filter(row=>row.ended).length})`:`Hide ended farms (${rows.filter(row=>row.ended).length})`}</button><button disabled={busy||state.loading} onClick={()=>setRetry(v=>v+1)}>Refresh farms</button><button className="exchange-primary" disabled={busy||state.loading||!rows.some(row=>!/^0+$/.test(row.raw))} onClick={()=>prepare(null)}>{busy?'Preparing...':'Claim all'}</button></div></div>
 {(state.error||error)&&<p className="exchange-error" role="alert">{error||state.error}</p>}
 {tx&&<p className="exchange-success" role="status">Farm transaction submitted. {/^[a-f0-9]{64}$/.test(tx)&&<a href={`https://waxblock.io/transaction/${tx}`} target="_blank" rel="noreferrer">View transaction</a>}</p>}
 <div className="farm-rows">{visibleRows.map(row=><article className="farm-row" key={`${row.incentiveId}:${row.posId}`}><div><strong><TokenLogo token={row.group.tokenA}/><TokenLogo token={row.group.tokenB}/>{row.group.tokenA?.symbol||`Pool ${row.poolId}`} / {row.group.tokenB?.symbol||''}</strong><small>Position #{row.posId} · Farm #{row.incentiveId}</small><small>{row.ended?'Farm ended':'Farm active'}{row.inRange===false?' · Position out of range':''}</small></div><div className="farm-reward"><small>{row.ended?'Final estimate':stale?'Estimate paused':'Live estimate'}</small><strong><TokenLogo token={row.token}/>{row.amount} {row.token.symbol}</strong><small>{row.token.contract}</small><details className="farm-token-info"><summary>Token info</summary>{[...new Map([row.group.tokenA,row.group.tokenB,row.token].filter(Boolean).map(t=>[`${t.symbol}@${t.contract}`,t])).values()].map(token=><div key={`${token.symbol}@${token.contract}`}><strong><TokenLogo token={token}/>{token.symbol}</strong><p>{tokenMetadata(token)?.description||'This token is part of this Alcor farm. A project description is not available in CleanupCentr.'}</p><small>{tokenMetadata(token)?.role||'External token'} · {token.precision} decimals</small><a href={`https://waxblock.io/account/${token.contract}`} target="_blank" rel="noreferrer">{token.contract} ↗</a></div>)}</details></div><div className="farm-row-actions"><button className="exchange-primary" disabled={busy||/^0+$/.test(row.raw)} onClick={()=>prepare(row)}>Review claim</button><button disabled={busy||state.loading} onClick={()=>prepare(row,true)}>Unstake from farm</button></div></article>)}</div>
 {hideEnded&&rows.some(row=>row.ended)&&<p className="exchange-muted">{rows.filter(row=>row.ended).length} ended farms hidden. Claim all still includes their available rewards.</p>}
 {!state.loading&&!state.error&&!state.rows.length&&<p>No staked farm positions found for this wallet. Stake a liquidity position on Alcor to earn farm rewards.</p>}
 {state.updatedAt&&<p className="exchange-muted">{stale?'Live estimates paused because the last refresh is over two minutes old. Refresh to resume.':'Live estimates update every second; chain data refreshes every minute.'} Rewards calculated from Alcor contract data · Updated {new Date(state.updatedAt).toLocaleTimeString()}. Position discovery uses the Alcor index and may lag. The contract determines the final claimed amount.</p>}
 </>}
 {review&&<dialog ref={dialog} className="exchange-review farm-claim-review" aria-labelledby="farm-claim-title" onCancel={e=>{e.preventDefault();if(!busy)setReview(null);}}><h2 id="farm-claim-title">{review.unstake?'Review farm unstake':review.claims?'Review all farm claims':'Review farm claim'}</h2>{review.claims?<><p>{review.claims.length} reward claims in one transaction</p>{totalFarmRewards(review.claims).map(total=><p key={`${total.token.symbol}@${total.token.contract}`}><TokenLogo token={total.token}/><strong>Estimated: {total.amount} {total.token.symbol}</strong><br/><small>{total.token.contract}</small></p>)}<details><summary>Included farm positions</summary>{review.claims.map(c=><p key={`${c.incentiveId}:${c.posId}`}>Position #{c.posId} · Farm #{c.incentiveId} · {c.amount} {c.token.symbol}</p>)}</details></>:<><p><TokenLogo token={review.token}/><strong>Estimated: {review.amount} {review.token.symbol}</strong></p><p className="exchange-muted">Position #{review.posId} · Farm #{review.incentiveId}<br/>{review.token.symbol}@{review.token.contract}</p></>}<p>To wallet: {actor}</p><p className="exchange-muted">{review.unstake?'Claims remaining farm rewards and removes this position from this reward farm only. Your liquidity stays in the pool, and other farm memberships remain unchanged.':'Your liquidity stays staked. Rewards may change until the transaction is processed.'}</p><p>{now>=review.expiresAt?'Review expired. Close and review again.':`Review valid for ${Math.ceil((review.expiresAt-now)/1000)}s`}</p><div className="exchange-review-actions"><button disabled={busy} onClick={()=>setReview(null)}>Cancel</button><button className="exchange-primary" disabled={busy||now>=review.expiresAt} onClick={confirm}>{busy?'Waiting for wallet...':'Confirm in wallet'}</button></div></dialog>}
 </section>;
}