import React,{useState,useEffect,useRef} from 'react';
import TokenLogo from './TokenLogo';
import {quoteDustConversion,executeDustConversion} from '../services/alcorMainnet';
import {formatRaw} from '../services/exchangeMath';
export default function DustConversion({actor,tokens,onClose,onComplete}) {
 const dialog=useRef(),lock=useRef(false);const [selected,setSelected]=useState(''),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());
 const eligible=tokens.filter(t=>!(t.symbol==='TRASH'&&t.contract==='cleanuptoken')&&(t.valueUSD===null||t.valueUSD<1));
 const token=eligible.find(t=>t.key===selected);
 useEffect(()=>{dialog.current.showModal();const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 async function prepare(){if(lock.current||!token)return;lock.current=true;setBusy(true);setError('');setReview(null);try{setReview(await quoteDustConversion(actor,token));setNow(Date.now());}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 async function confirm(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const result=await executeDustConversion(review,actor);onComplete(result);}catch(e){setReview(null);setError(e.message);}finally{lock.current=false;setBusy(false);}}
 const q=review?.quote;
 return <dialog ref={dialog} className="exchange-review portfolio-liquidity" aria-labelledby="dust-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2 id="dust-title">Convert dust to TRASH</h2><p>Convert one token at a time. Choose a holding below $1 in estimated value, or an unpriced token. Nothing is selected automatically.</p>
 {error&&<p role="alert" className="exchange-error">{error}</p>}
 {!review?<><label className="wallet-search">Token to convert<select disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setError('');}}><option value="">Choose a token</option>{eligible.map(t=><option key={t.key} value={t.key}>{t.symbol} · {t.exactAmount} · {t.contract}{t.valueUSD===null?' · Unpriced':''}</option>)}</select></label>{token&&<p><TokenLogo token={token}/>Convert your verified {token.symbol} balance, reserving any supported token transfer fees. This trades tokens; it does not burn them.</p>}<p className="exchange-muted">Compares available direct and two-pool paths through supported exchange tokens. Quotes include pool fees. Slippage: 0.5%; price impact limit: 5%. Very small balances may not be tradable.</p></>:<><p>You pay <strong>{review.params.amount} {q.inputToken.symbol}</strong><br/><small>{q.inputToken.contract}</small></p>{review.params.transferFeeReserve && review.params.transferFeeReserve!=="0" && <p>Reserved for token transfer fees: <strong>{formatRaw(review.params.transferFeeReserve,q.inputToken)} {q.inputToken.symbol}</strong><br/><small>Includes rounding allowance. Any unused amount stays in your wallet.</small></p>}<p>Estimated receive <strong>{formatRaw(q.outputRaw,q.outputToken)} TRASH</strong></p><p>Minimum received: {formatRaw(q.minimum,q.outputToken)} TRASH<br/>Price impact: {(q.impactBps/100).toFixed(2)}%</p><p>Route: {q.inputToken.symbol}{q.hops.map(h=>` → ${h.outputToken.symbol}`).join('')}<br/><small>Pools: {q.route.join(' → ')}</small></p><p>{q.coverage.quoted} of {q.coverage.total} candidate routes quoted. Best output among successful quotes.</p><p>Recipient: {actor}<br/>{now>=q.expiresAt?'Quote expired. Review again.':`Quote expires in ${Math.ceil((q.expiresAt-now)/1000)}s`}</p></>}
 <div className="exchange-review-actions"><button disabled={busy} onClick={review?()=>setReview(null):onClose}>{review?'Back':'Close'}</button>{review?<button className="exchange-primary" disabled={busy||now>=q.expiresAt} onClick={confirm}>{busy?'Waiting for wallet…':'Confirm in wallet'}</button>:<button className="exchange-primary" disabled={busy||!token} onClick={prepare}>{busy?'Comparing routes…':'Review conversion'}</button>}</div></dialog>;
}