import React from 'react';
import {render,screen,fireEvent,act} from '@testing-library/react';
import '@testing-library/jest-dom';
import DustConversion from './DustConversion';
import {quoteDustConversion,executeDustConversion} from '../services/alcorMainnet';
import {TOKENS} from '../services/exchangeMath';
jest.mock('../services/alcorMainnet',()=>({quoteDustConversion:jest.fn(),executeDustConversion:jest.fn()}));
const input={key:'yeet',symbol:'YEET',contract:'token.yeet',precision:8,exactAmount:'0.04195052',valueUSD:0.01};
const hops=[{poolId:'4512',inputToken:input,outputToken:TOKENS[4],fee:3000},{poolId:'11803',inputToken:TOKENS[4],outputToken:TOKENS[0],fee:10000},{poolId:'4804',inputToken:TOKENS[0],outputToken:TOKENS[2],fee:10000}];
const review=()=>({params:{amount:'0.04195052'},quote:{kind:'swap',inputToken:input,outputToken:TOKENS[2],outputRaw:'119675231',minimum:'119076854',impactBps:40,slippageBps:50,hops,route:hops.map(h=>h.poolId),coverage:{quoted:61,total:83},expiresAt:Date.now()+30000}});
beforeEach(()=>{jest.clearAllMocks();HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};quoteDustConversion.mockImplementation(async()=>review());});
afterEach(()=>jest.useRealTimers());
test('shows the reviewed route and refreshes expired quotes without dispatching a swap',async()=>{
 jest.useFakeTimers();
 render(<DustConversion actor="maestrobeatz" tokens={[input]} onClose={jest.fn()} onComplete={jest.fn()}/>);
 fireEvent.change(screen.getByLabelText('Token to convert'),{target:{value:'yeet'}});
 fireEvent.click(screen.getByRole('button',{name:'Review conversion'}));
 await act(async()=>{});
 expect(screen.getByRole('region',{name:'Swap route'})).toHaveTextContent('YEET');
 expect(screen.getByRole('region',{name:'Swap route'})).toHaveTextContent('BANANAZ');
 expect(screen.getByText('3 pools')).toBeInTheDocument();
 expect(screen.getByText('119076.854 TRASH')).toBeInTheDocument();
 expect(screen.getByText('Pool details · fees included').closest('details')).not.toHaveAttribute('open');
 act(()=>jest.advanceTimersByTime(31000));
 expect(screen.queryByRole('button',{name:'Confirm in wallet'})).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Refresh quote'}));
 await act(async()=>{});
 expect(quoteDustConversion).toHaveBeenCalledTimes(2);
 expect(executeDustConversion).not.toHaveBeenCalled();
 expect(screen.getByRole('button',{name:'Confirm in wallet'})).toBeEnabled();
});
